version: "3"
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    command: sh -c "sh start.sh"
    ports:
      - "3000:3000"
